### ISSUE TITLE
Splitting Functionality and Modification of Vanilla Blocks

### ISSUE THREAD

**Issue by CheaterCodes** [Virtuoel/Towelette#14]
I already asked about it in discord but I'll put it here for reference.

I'd like to implement fluid logging on some of my blocks, but don't want to force the modification of vanilla blocks for all modpacks using my mod. I suggest moving the altering of vanilla block behaviour into a seperate mod or moving more of the functionality into the API.

**Comment by Virtuoel** [comment]
Closed in 985292a
