### ISSUE TITLE
Some lavalogged blocks still emit embers when they shouldn't

### ISSUE THREAD

**Issue by muzikbike** [Virtuoel/Towelette#27]
These lavalogged top slabs don't have any exposed lava, for example, yet still shoot out embers:

![2020-06-27_21 35 01](https://user-images.githubusercontent.com/52297970/85931728-64a42f00-b8be-11ea-8a87-c97c4654ff7b.png)
![2020-06-27_21 35 04](https://user-images.githubusercontent.com/52297970/85931729-65d55c00-b8be-11ea-8263-2e51d024def5.png)
![2020-06-27_21 36 42](https://user-images.githubusercontent.com/52297970/85931730-666df280-b8be-11ea-86b0-a37b307c9941.png)

**Comment by Virtuoel** [comment]
Should now be resolved in the most recent update.
