### ISSUE TITLE
File 1.14 1.6.0 was created May 18, where is the latest file?

### ISSUE THREAD

**Issue by Dragonracer1973** [Virtuoel/Towelette#3]
Not trying to sound snarky, just wondering as the file I currently have is that version

**Comment by Virtuoel** [comment]
There were some issues with the file uploading part of my buildscript, so the files that were uploaded to CurseForge more recently were not the proper files and had to be removed. The newer versions shall be there once I fix the issue. Apologies for the delay and confusion.

**Comment by Virtuoel** [comment]
Latest file shall be up momentarily.
