### ISSUE TITLE
Incompatibility with Immersive Portals when on a server.

### ISSUE THREAD

**Issue by BNTFryingPan** [Virtuoel/Towelette#32]
See post at [qouteall/ImmersivePortalsMod #413](qouteall/ImmersivePortalsMod)

tl;dr
When waterlogging blocks, the block either is rendered as a random other block or it is rendered in the wrong block state (eg, upside down stair instead of normal stair), or the liquid is the wrong liquid, and sometimes both occur.

I'm not sure if this is something that needs to be fixed in Towelette or in Immersive Portals.

**Comment by Virtuoel** [comment]
Appears to be resolved when using the latest Immersive Portals with Towelette's 5.0.0 release.
