### ISSUE TITLE
[Bug]: Safe Mode Datapack Error When Joining or Creating World

### ISSUE THREAD

**Issue by emoace** [Virtuoel/Towelette#35]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

0.11.6

### Fabric API version

0.36.1

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Expected - Join or Create world like normal

What Happened - "Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually."

### Full list of installed mods

[22:31:43] [main/INFO]: [FabricLoader] Loading 214 mods:
	- accurateblockplacement@1.0.10
	- adorn@2.1.3+1.17.1
	- advanced_runtime_resource_pack@0.4.3
	- adventurez@1.2.9
	- alloy_forgery@2.0.0
	- alternate-current@0.2.0
	- aqupd@1.17-1.2.2
	- aqupdgrizzly@1.1.1
	- architects_palette@1.2
	- architectury@2.2.21
	- assembly@21w07a-1.1.0
	- attributefix@1.0.1
	- autoconfig1u@3.3.1
	- axolotlitemfix@1.1.1
	- bclib@0.2.4
	- beaconoverhaul@1.4.1+1.17
	- bedrockify@1.1.1+mc1.17
	- bedspreads@1.4.0-1.17
	- betterbiomeblend@1.17.0-1.1.9-fabric
	- betterend@0.10.5-pre
	- bettermineshafts@1.17-1.0.0
	- betterstrongholds@1.17-1.1
	- bitsandchisels@2.5.0
	- blastrod@1.1.0+1.17
	- blockus@2.2.7+1.17.1
	- boats-and-beeps@1.0.1
	- canvas@1.0.1753
	- cardinal-components-base@3.0.1
	- cardinal-components-entity@3.0.1
	- cardinal-components-item@3.0.1
	- cavebiomeapi@1.2.0
	- charm@3.3.2
	- charmonium@3.3.0
	- cleancut@1.17-4.0-fabric
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.34
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- clumps@fabric-1.17-7.0.0.2
	- coloredslime@1.2.6
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- conjuring@1.0.5
	- connectiblechains@1.2.2
	- controlling@1.1.2
	- cpas@2.0.0
	- cpas-api@2.0.0
	- cpas-runtime@2.0.0
	- cullleaves@2.2.0
	- dangerousstonecutter@1.5
	- disable_custom_worlds_advice@1.3
	- ducts@1.1.4
	- dynamicfps@2.0.4
	- easyautocrafting@1.1+1.17
	- endermenarefriends@1.1-mc1.17-fabric
	- enhanced_mushrooms@1.0.5
	- enhancedblockentities@0.4.1+1.17
	- extrasounds@1.4.1
	- fabric@0.36.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d013
	- fabric-biome-api-v1@3.1.11+c345aea813
	- fabric-blockrenderlayer-v1@1.1.5+a02b446313
	- fabric-command-api-v1@1.1.2+6cefd57713
	- fabric-commands-v0@0.2.2+92519afa13
	- fabric-containers-v0@0.1.12+a02b446313
	- fabric-content-registries-v0@0.2.2+a02b446313
	- fabric-crash-report-info-v1@0.1.5+be9da31013
	- fabric-dimensions-v1@2.0.11+6cefd57713
	- fabric-entity-events-v1@1.1.0+a02b446313
	- fabric-events-interaction-v0@0.4.9+a722d8c013
	- fabric-events-lifecycle-v0@0.2.1+92519afa13
	- fabric-game-rule-api-v1@1.0.7+6cefd57713
	- fabric-item-api-v1@1.2.4+a02b446313
	- fabric-item-groups-v0@0.2.10+b7ab612113
	- fabric-key-binding-api-v1@1.0.4+a02b446313
	- fabric-keybindings-v0@0.2.2+36b77c3e13
	- fabric-language-kotlin@1.6.2+kotlin.1.5.20
	- fabric-lifecycle-events-v1@1.4.4+a02b446313
	- fabric-loot-tables-v1@1.0.4+a02b446313
	- fabric-mining-levels-v0@0.1.3+92519afa13
	- fabric-models-v0@0.3.0+a02b446313
	- fabric-networking-api-v1@1.0.12+6cefd57713
	- fabric-networking-blockentity-v0@0.2.11+a02b446313
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+b7ab612113
	- fabric-object-builders-v0@0.7.3+a02b446313
	- fabric-particles-v1@0.2.4+a02b446313
	- fabric-registry-sync-v0@0.7.10+e2961fee13
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446313
	- fabric-renderer-registries-v1@3.2.0+a02b446313
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446313
	- fabric-rendering-v0@1.1.2+92519afa13
	- fabric-rendering-v1@1.6.0+a02b446313
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+a02b446313
	- fabric-structure-api-v1@1.1.12+6cefd57713
	- fabric-tag-extensions-v0@1.1.4+a02b446313
	- fabric-textures-v0@1.0.6+a02b446313
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612113
	- fabricenchantments@0.3.2
	- fabricloader@0.11.6
	- fallingleaves@1.7.2+1.17
	- fastdecay@1.0.0
	- fermion@2.11.243
	- fermion-orientation@1.2.243
	- fermion-varia@2.6.243
	- ferritecore@3.0.1
	- fiber@0.23.0-2
	- fishonaleash@1.17-1.0.0
	- flagbric@2.0.0
	- frex@5.2.225
	- geckolib3@3.0.8
	- glassential@1.17-1.2.0
	- grondag_bitraster@1.3.11
	- ignis-fatuus@1.1.4
	- illuminations@1.6.1
	- impaled@1.0.1
	- indypets@0.5.0
	- itemmodelfix@1.0.2+1.17
	- jankson@3.0.1+j1.2.0
	- java@16
	- json-model-extensions@1.22.201
	- kanos_config@0.1.4+1.14.4-1.17.1
	- kirin@1.8.7-1.17
	- krypton@0.1.4
	- lazydfu@0.1.2
	- libblockattributes@0.9.0-pre.2
	- libblockattributes_core@0.9.0-pre.2
	- libblockattributes_fluids@0.9.0-pre.2
	- libblockattributes_items@0.9.0-pre.2
	- libcd@3.0.3+1.16.3
	- libgui@4.1.4+1.17.1
	- libninepatch@1.1.0
	- lithium@0.7.3
	- lovely_snails@1.0.2+1.17
	- maelstrom_library@1.2.1-1.17-pre1
	- mavm@1.0.2b
	- maybe-data@1.0.1-1.17
	- mcct@1.4.0-1.17
	- minecraft@1.17.1
	- miniextras@1.3.3+1.17.1
	- mob_proof_crystals@2.2.0
	- mobs_attempt_parkour@0.2.3-1.17-pre1
	- modmenu@2.0.4
	- morevillagers-fabric@2.0.4-SNAPSHOT
	- mostructures@1.2.1-1.17
	- multipart-entities@1.0.2
	- netherchest@2.0
	- nethermap@1.4.0-1.17.1
	- no-potion-offset@${version}
	- nostrip@1.2.1-1.17+
	- omega-config@1.0.8
	- onsoulfire@1.17-2
	- openloader@2.0.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.20
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- org_json_json@20210307
	- owo@0.1.1
	- paradoxslabs@0.1.1
	- particlerain@1.3.1
	- patchouli@1.17-54-FABRIC
	- pettable@1.2.0
	- powershot@1.2.0-1.17-fabric
	- ratsmischief@1.2
	- reach-entity-attributes@2.1.1
	- realisticfirespread@1.17-2
	- recipecache@0.2.0-1.17.1
	- repurposed_structures@2.1.6+1.17.1
	- right-click-clear@2.0.3
	- roughlyenoughitems@6.0.264-alpha
	- sihywtcamc@1.3.1+1.17.1
	- skinnedlanterns@1.1.5
	- slotlock@1.0.4-BETA+1.17
	- soundphysics@2.0.0
	- special-circumstances@1.9.243
	- spyzoom@1.0.1
	- stacc@1.0.1
	- statement@4.1.1+1.14.4-1.17.1
	- statement_vanilla_compatibility@1.0.1+1.16.5-1.17
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- stickyhopper@2.3-1.17-1
	- stoneholm@1.3
	- stonevaults@1.1.0
	- totemicoverhaul@1.1.7
	- towelette@4.2.2+1.14.4-1.17.1
	- transportables@1.0.5
	- trumpet-skeleton@1.1.4
	- untitledduckmod@0.3.0
	- villagerfix@2.1.3+1.17
	- voicechat@1.17.1-1.0.10
	- voidfog@2.5.1-1.17-rc1
	- waterdripsound@1.17-0.2.2
	- waystones@2.0.2
	- wolveswitharmor@1.6.0-1.17
	- xlpackets@1.1
	- xp_storage@1.4.2+1.17.1
	- yungsapi@1.17-Fabric-13

Datapacks used with Openloader: 
- afk display v1.1.0.zip
- armor statues v2.8.1.zip
- c-c-expansionpack-1-5-1.zip
- cauldron concrete v2.0.3.zip
- chunk loaders v1.0.1.zip
- custom nether portals v2.3.2.zip
- gem villagers v4.3.3.zip
- ichphilipp-s-endcity-v1-1-1-16-2.zip
- larger phantoms v1.2.1.zip
- more mob heads v2.9.2.zip
- player head drops v1.1.0.zip
- Repurposed_Structures-Charm.zip
- silence mobs v1.1.0.zip
- treasure gems v1.2.2.zip
- wandering trades v1.5.0.zip

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by emoace** [comment]
This also occurs when using [1.17.1] Fabric API 0.37.1

**Comment by ArcusMG** [comment]
Same issue here. 

Mods installed:
adventurez-1.2.10.jar
agape_space_17-0.2.14.jar
architectury-2.3.24-fabric.jar
autoconfig1u-3.3.1.jar
bclib-0.3.0.jar
better-end-0.11.0-pre.jar
BetterMineshafts-Fabric-1.17-1.0.1.jar
BetterStrongholds-Fabric-1.17-1.1.1.jar
betterthanmending-1.3.0.jar
bitsandchisels-2.5.3.jar
blame-1.17-4.0.1-fabric.jar
blockus-2.2.8+1.17.1.jar
Blur-2.2.1-1.17+fabric.jar
boats-and-beeps-1.0.3.jar
BuildGuide-Fabric-1.17.1-0.2.3.jar
can-i-mine-this-block-1.1.0.jar
canvas-mc117-1.17-1.0.1895.jar
Cardinal-Components-API-3.1.1.jar
carrier-1.8.0.jar
charm-fabric-1.17-3.3.2.jar
charmonium-fabric-1.17-3.3.0.jar
CleanView-1.17.1-v1-fabric.jar
cloth-api-2.0.54.jar
cloth-config-5.0.38-fabric.jar
Clumps-fabric-1.17.1-7.0.4.jar
companion-bats-fabric-1.17.5.jar
conjuring-1.0.7.jar
Couplings-1.5.1+1.17.jar
Croptopia-1.17-FABRIC-1.6.1.jar
dankstorage-2.1-1.17.1.jar
dark-loading-screen-1.6.6.jar
DarkPaintings-fabric-1.17.1-4.0.2.jar
dawn-2.0.5.jar
deepmoblearning-refabricated-0.4.4-beta.jar
diggusmaximus-1.4.5-1.17.jar
DisableCustomWorldsAdvice-1.3.jar
disenchanter-1.0.0.jar
dmlSimulacrum-1.0.3.jar
dst-origins-1.17.1.jar
ducts-1.1.4.jar
DungeonsArise-1.17.1-2.1.47-fabric-release.jar
enchantedbookredesign-1.17.1-2.0.jar
enchantment-lore-1.2+MC1.17.1.jar
EnvironmentalArmor-1.17.1-1.4.0.jar
expanded-axe-enchanting-1.0.2.jar
extraorigins-1.17-6.jar
fabric-api-0.37.2+1.17.jar
fabric-language-kotlin-1.6.3+kotlin.1.5.21.jar
fallingleaves-1.7.2+1.17.jar
ferritecore-3.0.1-fabric.jar
GearReborn-1.17-0.1.8.jar
geckolib-fabric-1.17-3.0.11.jar
glowingbanners-1.0.2.jar
GuardiansGalore-1.17.1-2.0.jar
hookshot-r18.jar
illuminations-1.6.3.jar
illuminations-uninstaller.jar
impersonate-2.3.3.jar
indrev-1.10.0-alpha.12.jar
infinityfix-1.1.0.jar
IronChests-1.4.0.jar
item-model-fix-1.0.2+1.17.jar
itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506.jar
kibe-1.8-BETA+1.17.jar
lacrimis-2.1.3+1.17.1.jar
lithium-fabric-mc1.17.1-0.7.3.jar
lovely_snails-1.0.3+1.17.jar
magicfungi-0.1.0-BETA+1.17.1.jar
malilib-fabric-1.17.1-0.10.0-dev.24.jar
mcda-1.7.6.jar
mcdar-1.4.1.jar
MCDoom-Fabric-1.17-4.0.1.jar
mcdw-3.3.5.jar
mcwifipnp-1.3.6-1.17.1-fabric.jar
medieval_origins-1.1.1.jar
megane-5.2.0.jar
MobCatcher-Fabric-1.17.1-1.0.8.jar
moborigins-1.6.0.jar
Modern-Industrialization-0.5.8.jar
modmenu-2.0.4.jar
morevillagers-FABRIC-1.17-2.0.4.jar
NaturesCompass-1.17.1-2.0.1-fabric.jar
nauticality-0.1.2.jar
nears-1.17-1.1.2.jar
npc-variety-1.17.0-2.1.2.jar
Origins-1.17-1.0.3.jar
Origins-Classes-1.17-1.2.2.jar
outvoted-2.0.0-alpha.11-fabric.jar
pal-1.3.0.jar
Patchouli-1.17-54-FABRIC.jar
Pehkui-2.3.0+1.14.4-1.17.1.jar
PetOwner-1.8.1-1.17-rc1+.jar
plantinajar-2.2.2.jar
pling-1.4.0.jar
quarry-reborn-1.17-0.1.0.jar
quartz-elevator-1.2.5-1.17.1.jar
RebornCore-5.0.5-beta+build.85.jar
respawnablepets-1.17-3.jar
right-click-clear-2.0.3.jar
RoughlyEnoughItems-6.0.264-alpha-fabric.jar
rswires-4.11.2.jar
Schmucks-1.17-1.4.0.jar
scorch-1.0.2.jar
seamless-loading-screen-1.3.6+1.17.1.jar
somnus-fabric-0.0.12-1.17.jar
spatialharvesters_Fabric_1.17.x-0.11.12a.jar
Statement-4.1.2+1.14.4-1.17.1.jar
stuffz-2.3.2.jar
TechReborn-5.0.5-beta+build.85.jar
the_bumblezone_fabric-3.0.9+1.17.1.jar
TheVeggieWay_Fabric-1.17.1-1.1.18.jar
things-0.2.3.jar
tomsstorage-1.1.13-1.17.1.jar
torohealth-1.17.1-fabric-11.jar
Towelette-4.2.2+1.14.4-1.17.1.jar
traverse-4.0.0-beta.2.jar
trinkets-3.0.2.jar
true-secret-rooms-1.1.5.jar
visualoverhaul-3.3.0.jar
voidz-1.0.5.jar
wanderingcollector-1.0.2+mc1.17.jar
winged-1.17.1-3.0.0.jar
wirelessnetworks-1.1.2.jar
wraith-waystones-2.0.3.jar
wthit-fabric-3.8.1.jar
Xaeros_Minimap_21.14.0_Fabric_1.17.1.jar
XaerosWorldMap_1.15.0.1_Fabric_1.17.1.jar
YungsApi-1.17-Fabric-15.jar

**Comment by Virtuoel** [comment]
Potentially resolved with Towelette's 5.0.0 release. If the issue persists in newer MC, please create a new issue with your `latest.log` file in a comment as well.
