### ISSUE TITLE
[Bug]: Pistons disappear

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Towelette#36]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.11.6

### Fabric API version

Fabric API 0.37.2

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

When pistons get activated , they disappear.  
you can't place blocks where they were  , placing blocks by hand doesn't work , dropping sand where it was doesn't work , placing water nearby doesn't work , trying to push it using a piston doesn't work , exiting and entering world doesn't work and restarting the game doesn't work.
only way to "fix" the invisible block is to /fill or /setblock

if you need any extra info leave a comment. 
![RBLI6ir2M1](https://user-images.githubusercontent.com/64341475/129457911-6038dcc0-4006-4ce0-8801-d57fd46bbecd.gif)

### Full list of installed mods

Fabric API 0.37.2
Statement 4.1.3
Towelette 4.2.2

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by midnight771** [comment]
i am having the same problem

**Comment by Virtuoel** [comment]
Resolved as of Towelette's 5.0.0 release.
