### ISSUE TITLE
[Error]: Update to 1.19.2 please? And what is fabric-tag-extention?

### ISSUE THREAD

**Issue by Psychodeus** [Virtuoel/Towelette#38]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.19.2

### Mod loader

Fabric

### Mod loader version

-

### Fabric API version

-

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

-

### Full list of installed mods

-

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

![image](https://user-images.githubusercontent.com/93028949/195808276-8c55b1a7-f99d-445b-b914-a65bc2aff297.png)
I can't found it anywhere to download.

**Comment by Virtuoel** [comment]
Resolved as of Towelette's 5.0.0 release.
