### ISSUE TITLE
Incompatible with 1.20.1

### ISSUE THREAD

**Issue by PurpleCrowbar** [Virtuoel/Towelette#40]
Are there any plans to update Towelette to 1.20.1? I only ask because it's been a few months since its release and the creator still appears to be active on GitHub / CurseForge

**Comment by OnyxXIII** [comment]
+1. Tested on 1.20.4 and it crashes on load.

Not to press or anything, but I just wanted to add that I would be ecstatic to have this working! Our server runs this along with a small number of other mods, which are all up to 1.20
(Just commenting to let the author know this mod is loved)

**Comment by Virtuoel** [comment]
Should now be resolved as of the 5.0.1 release.
