### ISSUE TITLE
Will this be updated to 1.20.1?

### ISSUE THREAD

**Issue by CriochDev** [Virtuoel/Towelette#45]
I heard on the Fabric discord that this was potentially deprecated, so I wanted to confirm whether that was true or not.

**Comment by Virtuoel** [comment]
I'm not sure what you mean by "updated to 1.20.1". It already works on 1.20.1. If you mean 1.20.6 or 1.21, it will be, though I've just been preoccupied with other things and also updating my other mods first in the meantime.
