### ISSUE TITLE
Certain currently non-waterloggable non-full blocks should be made waterloggable

### ISSUE THREAD

**Issue by muzikbike** [Virtuoel/Towelette#6]
This includes farmland, grass paths, pistons, piston heads, and shulker boxes. Leaves may also be included.

**Comment by Virtuoel** [comment]
Farmland and paths are only one pixel lower than a full block. When waterlogged, the water level isn't high enough to show up. 
When Pistons move blocks, the fluid they contain is removed, so waterlogging them to have the water removed when they move doesn't seem too useful.

I'll still look into adding configs for these, though I'll likely have them off by default.

**Comment by muzikbike** [comment]
The issue with farmland and grass paths becomes a bit more clear when the blocks are placed underwater, since water occupies a full cube at lower depths.

**Comment by Virtuoel** [comment]
Configs for this have been added as of 1.8.0.
